<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AdminPermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('admin_permissions')->delete();
        
        \DB::table('admin_permissions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => '认证管理',
                'slug' => 'auth-management',
                'http_method' => '',
                'http_path' => '',
                'order' => 1,
                'parent_id' => 0,
                'created_at' => '2020-09-18 09:45:49',
                'updated_at' => '2020-11-18 17:45:54',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => '管理员管理',
                'slug' => 'users',
                'http_method' => '',
                'http_path' => '/auth/users*',
                'order' => 2,
                'parent_id' => 1,
                'created_at' => '2020-09-18 09:45:49',
                'updated_at' => '2020-11-18 17:46:18',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => '角色管理',
                'slug' => 'roles',
                'http_method' => '',
                'http_path' => '/auth/roles*',
                'order' => 3,
                'parent_id' => 1,
                'created_at' => '2020-09-18 09:45:49',
                'updated_at' => '2020-11-18 17:46:10',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => '权限管理',
                'slug' => 'permissions',
                'http_method' => '',
                'http_path' => '/auth/permissions*',
                'order' => 4,
                'parent_id' => 1,
                'created_at' => '2020-09-18 09:45:49',
                'updated_at' => '2020-11-18 17:46:26',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => '菜单管理',
                'slug' => 'menu',
                'http_method' => '',
                'http_path' => '/auth/menu*',
                'order' => 5,
                'parent_id' => 1,
                'created_at' => '2020-09-18 09:45:49',
                'updated_at' => '2020-11-18 17:46:33',
            ),
            5 => 
            array (
                'id' => 7,
                'name' => '动作',
                'slug' => 'device.action',
                'http_method' => '',
                'http_path' => '',
                'order' => 9,
                'parent_id' => 14,
                'created_at' => '2020-11-19 08:57:47',
                'updated_at' => '2020-11-19 13:32:55',
            ),
            6 => 
            array (
                'id' => 8,
                'name' => '设备删除',
                'slug' => 'device.record.delete',
                'http_method' => '',
                'http_path' => '',
                'order' => 10,
                'parent_id' => 7,
                'created_at' => '2020-11-19 08:58:10',
                'updated_at' => '2020-11-19 13:24:56',
            ),
            7 => 
            array (
                'id' => 9,
                'name' => '设备归属',
                'slug' => 'device.track.create_update',
                'http_method' => '',
                'http_path' => '',
                'order' => 12,
                'parent_id' => 7,
                'created_at' => '2020-11-19 08:58:23',
                'updated_at' => '2020-12-28 16:24:30',
            ),
            8 => 
            array (
                'id' => 10,
                'name' => '设备归属解除',
                'slug' => 'device.track.delete',
                'http_method' => '',
                'http_path' => '',
                'order' => 13,
                'parent_id' => 7,
                'created_at' => '2020-11-19 08:59:02',
                'updated_at' => '2020-12-28 16:24:30',
            ),
            9 => 
            array (
                'id' => 13,
                'name' => '设备故障',
                'slug' => 'device.maintenance.create',
                'http_method' => '',
                'http_path' => '',
                'order' => 16,
                'parent_id' => 7,
                'created_at' => '2020-11-19 09:23:03',
                'updated_at' => '2020-12-28 16:24:30',
            ),
            10 => 
            array (
                'id' => 14,
                'name' => '设备管理',
                'slug' => 'device',
                'http_method' => '',
                'http_path' => '',
                'order' => 6,
                'parent_id' => 0,
                'created_at' => '2020-11-19 09:55:45',
                'updated_at' => '2020-11-19 13:11:45',
            ),
            11 => 
            array (
                'id' => 15,
                'name' => '软件管理',
                'slug' => 'software',
                'http_method' => '',
                'http_path' => '',
                'order' => 17,
                'parent_id' => 0,
                'created_at' => '2020-11-19 09:59:31',
                'updated_at' => '2020-12-28 16:24:30',
            ),
            12 => 
            array (
                'id' => 16,
                'name' => '配件管理',
                'slug' => 'part',
                'http_method' => '',
                'http_path' => '',
                'order' => 27,
                'parent_id' => 0,
                'created_at' => '2020-11-19 09:59:57',
                'updated_at' => '2020-12-28 16:25:16',
            ),
            13 => 
            array (
                'id' => 17,
                'name' => '组织管理',
                'slug' => 'staff',
                'http_method' => '',
                'http_path' => '',
                'order' => 37,
                'parent_id' => 0,
                'created_at' => '2020-11-19 10:00:31',
                'updated_at' => '2020-12-29 23:52:18',
            ),
            14 => 
            array (
                'id' => 18,
                'name' => '服务管理',
                'slug' => 'service',
                'http_method' => '',
                'http_path' => '',
                'order' => 43,
                'parent_id' => 0,
                'created_at' => '2020-11-19 10:00:55',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            15 => 
            array (
                'id' => 19,
                'name' => '盘点管理',
                'slug' => 'check',
                'http_method' => '',
                'http_path' => '',
                'order' => 52,
                'parent_id' => 0,
                'created_at' => '2020-11-19 10:01:27',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            16 => 
            array (
                'id' => 20,
                'name' => '物资故障',
                'slug' => 'maintenance',
                'http_method' => '',
                'http_path' => '',
                'order' => 59,
                'parent_id' => 0,
                'created_at' => '2020-11-19 10:01:59',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            17 => 
            array (
                'id' => 21,
                'name' => '厂商',
                'slug' => 'vendor',
                'http_method' => '',
                'http_path' => '',
                'order' => 64,
                'parent_id' => 0,
                'created_at' => '2020-11-19 10:03:42',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            18 => 
            array (
                'id' => 22,
                'name' => '购入途径',
                'slug' => 'purchased',
                'http_method' => '',
                'http_path' => '',
                'order' => 67,
                'parent_id' => 0,
                'created_at' => '2020-11-19 10:04:11',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            19 => 
            array (
                'id' => 23,
                'name' => '版本信息',
                'slug' => 'version',
                'http_method' => '',
                'http_path' => '',
                'order' => 70,
                'parent_id' => 0,
                'created_at' => '2020-11-19 10:04:37',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            20 => 
            array (
                'id' => 24,
                'name' => '动作',
                'slug' => 'software.action',
                'http_method' => '',
                'http_path' => '',
                'order' => 20,
                'parent_id' => 15,
                'created_at' => '2020-11-19 10:06:25',
                'updated_at' => '2020-12-28 16:24:30',
            ),
            21 => 
            array (
                'id' => 25,
                'name' => '软件删除',
                'slug' => 'software.record.delete',
                'http_method' => '',
                'http_path' => '',
                'order' => 21,
                'parent_id' => 24,
                'created_at' => '2020-11-19 10:09:16',
                'updated_at' => '2020-12-28 16:24:30',
            ),
            22 => 
            array (
                'id' => 26,
                'name' => '软件归属',
                'slug' => 'software.track.create_update',
                'http_method' => '',
                'http_path' => '',
                'order' => 23,
                'parent_id' => 24,
                'created_at' => '2020-11-19 10:09:40',
                'updated_at' => '2020-12-28 16:25:16',
            ),
            23 => 
            array (
                'id' => 27,
                'name' => '软件归属解除',
                'slug' => 'software.track.delete',
                'http_method' => '',
                'http_path' => '',
                'order' => 24,
                'parent_id' => 24,
                'created_at' => '2020-11-19 10:10:02',
                'updated_at' => '2020-12-28 16:25:16',
            ),
            24 => 
            array (
                'id' => 28,
                'name' => '软件变动履历',
                'slug' => 'software.history',
                'http_method' => '',
                'http_path' => '',
                'order' => 25,
                'parent_id' => 24,
                'created_at' => '2020-11-19 10:10:28',
                'updated_at' => '2020-12-28 16:25:16',
            ),
            25 => 
            array (
                'id' => 29,
                'name' => '软件管理归属',
                'slug' => 'software.track.list',
                'http_method' => '',
                'http_path' => '',
                'order' => 26,
                'parent_id' => 24,
                'created_at' => '2020-11-19 10:11:19',
                'updated_at' => '2020-12-28 16:25:16',
            ),
            26 => 
            array (
                'id' => 30,
                'name' => '动作',
                'slug' => 'part.action',
                'http_method' => '',
                'http_path' => '',
                'order' => 30,
                'parent_id' => 16,
                'created_at' => '2020-11-19 10:14:24',
                'updated_at' => '2020-12-28 16:25:16',
            ),
            27 => 
            array (
                'id' => 31,
                'name' => '配件删除',
                'slug' => 'part.record.delete',
                'http_method' => '',
                'http_path' => '',
                'order' => 31,
                'parent_id' => 30,
                'created_at' => '2020-11-19 10:15:02',
                'updated_at' => '2020-12-28 16:25:16',
            ),
            28 => 
            array (
                'id' => 32,
                'name' => '配件归属',
                'slug' => 'part.track.create_update',
                'http_method' => '',
                'http_path' => '',
                'order' => 33,
                'parent_id' => 30,
                'created_at' => '2020-11-19 10:15:12',
                'updated_at' => '2020-12-28 16:25:16',
            ),
            29 => 
            array (
                'id' => 33,
                'name' => '配件变动履历',
                'slug' => 'part.history',
                'http_method' => '',
                'http_path' => '',
                'order' => 35,
                'parent_id' => 30,
                'created_at' => '2020-11-19 10:15:27',
                'updated_at' => '2020-12-28 16:25:16',
            ),
            30 => 
            array (
                'id' => 34,
                'name' => '配件故障',
                'slug' => 'part.maintenance.create',
                'http_method' => '',
                'http_path' => '',
                'order' => 36,
                'parent_id' => 30,
                'created_at' => '2020-11-19 10:15:44',
                'updated_at' => '2020-12-28 16:25:16',
            ),
            31 => 
            array (
                'id' => 35,
                'name' => '配件归属解除',
                'slug' => 'part.track.delete',
                'http_method' => '',
                'http_path' => '',
                'order' => 34,
                'parent_id' => 30,
                'created_at' => '2020-11-19 10:16:04',
                'updated_at' => '2020-12-28 16:25:16',
            ),
            32 => 
            array (
                'id' => 36,
                'name' => '动作',
                'slug' => 'staff.action',
                'http_method' => '',
                'http_path' => '',
                'order' => 40,
                'parent_id' => 17,
                'created_at' => '2020-11-19 10:18:46',
                'updated_at' => '2020-12-28 16:25:16',
            ),
            33 => 
            array (
                'id' => 37,
                'name' => '雇员删除',
                'slug' => 'staff.record.delete',
                'http_method' => '',
                'http_path' => '',
                'order' => 41,
                'parent_id' => 36,
                'created_at' => '2020-11-19 10:18:57',
                'updated_at' => '2020-12-28 16:25:16',
            ),
            34 => 
            array (
                'id' => 38,
                'name' => '动作',
                'slug' => 'service.action',
                'http_method' => '',
                'http_path' => '',
                'order' => 46,
                'parent_id' => 18,
                'created_at' => '2020-11-19 10:19:54',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            35 => 
            array (
                'id' => 39,
                'name' => '服务删除',
                'slug' => 'service.record.delete',
                'http_method' => '',
                'http_path' => '',
                'order' => 47,
                'parent_id' => 38,
                'created_at' => '2020-11-19 10:20:16',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            36 => 
            array (
                'id' => 40,
                'name' => '服务归属',
                'slug' => 'service.track.create_update',
                'http_method' => '',
                'http_path' => '',
                'order' => 48,
                'parent_id' => 38,
                'created_at' => '2020-11-19 10:20:26',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            37 => 
            array (
                'id' => 41,
                'name' => '服务故障',
                'slug' => 'service.issue.create',
                'http_method' => '',
                'http_path' => '',
                'order' => 49,
                'parent_id' => 38,
                'created_at' => '2020-11-19 10:21:32',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            38 => 
            array (
                'id' => 42,
                'name' => '服务归属解除',
                'slug' => 'service.track.delete',
                'http_method' => '',
                'http_path' => '',
                'order' => 50,
                'parent_id' => 38,
                'created_at' => '2020-11-19 10:21:56',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            39 => 
            array (
                'id' => 43,
                'name' => '服务故障修复',
                'slug' => 'service.issue.update',
                'http_method' => '',
                'http_path' => '',
                'order' => 51,
                'parent_id' => 38,
                'created_at' => '2020-11-19 10:22:25',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            40 => 
            array (
                'id' => 44,
                'name' => '动作',
                'slug' => 'check.action',
                'http_method' => '',
                'http_path' => '',
                'order' => 55,
                'parent_id' => 19,
                'created_at' => '2020-11-19 10:29:48',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            41 => 
            array (
                'id' => 45,
                'name' => '盘点动作',
                'slug' => 'check.track.update',
                'http_method' => '',
                'http_path' => '',
                'order' => 56,
                'parent_id' => 44,
                'created_at' => '2020-11-19 10:30:28',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            42 => 
            array (
                'id' => 47,
                'name' => '动作',
                'slug' => 'maintenance.action',
                'http_method' => '',
                'http_path' => '',
                'order' => 62,
                'parent_id' => 20,
                'created_at' => '2020-11-19 10:31:18',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            43 => 
            array (
                'id' => 48,
                'name' => '物资故障修复',
                'slug' => 'maintenance.update',
                'http_method' => '',
                'http_path' => '',
                'order' => 63,
                'parent_id' => 47,
                'created_at' => '2020-11-19 10:31:43',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            44 => 
            array (
                'id' => 49,
                'name' => '盘点完成',
                'slug' => 'check.record.update.yes',
                'http_method' => '',
                'http_path' => '',
                'order' => 57,
                'parent_id' => 44,
                'created_at' => '2020-11-19 10:35:29',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            45 => 
            array (
                'id' => 50,
                'name' => '盘点取消',
                'slug' => 'check.record.update.no',
                'http_method' => '',
                'http_path' => '',
                'order' => 58,
                'parent_id' => 44,
                'created_at' => '2020-11-19 10:35:38',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            46 => 
            array (
                'id' => 51,
                'name' => '表单基础：只读',
                'slug' => 'device.read-only',
                'http_method' => 'GET',
                'http_path' => 'device/tracks*,device/records*,device/categories*',
                'order' => 7,
                'parent_id' => 14,
                'created_at' => '2020-11-19 13:18:12',
                'updated_at' => '2020-11-19 13:32:26',
            ),
            47 => 
            array (
                'id' => 52,
                'name' => '表单基础：全部',
                'slug' => 'device.all',
                'http_method' => '',
                'http_path' => 'device/tracks*,device/records*,device/categories*',
                'order' => 8,
                'parent_id' => 14,
                'created_at' => '2020-11-19 13:21:28',
                'updated_at' => '2020-12-19 01:19:54',
            ),
            48 => 
            array (
                'id' => 53,
                'name' => '表单基础：只读',
                'slug' => 'software.read-only',
                'http_method' => 'GET',
                'http_path' => 'software/tracks*,software/records*,software/categories*',
                'order' => 18,
                'parent_id' => 15,
                'created_at' => '2020-11-19 13:22:53',
                'updated_at' => '2020-12-28 16:24:30',
            ),
            49 => 
            array (
                'id' => 54,
                'name' => '表单基础：全部',
                'slug' => 'software.all',
                'http_method' => '',
                'http_path' => 'software/tracks*,software/records*,software/categories*',
                'order' => 19,
                'parent_id' => 15,
                'created_at' => '2020-11-19 13:23:56',
                'updated_at' => '2020-12-28 16:24:30',
            ),
            50 => 
            array (
                'id' => 55,
                'name' => '表单基础：只读',
                'slug' => 'hardware.read-only',
                'http_method' => 'GET',
                'http_path' => 'part/tracks*,part/records*,part/categories*',
                'order' => 28,
                'parent_id' => 16,
                'created_at' => '2020-11-19 13:37:36',
                'updated_at' => '2020-12-28 16:25:16',
            ),
            51 => 
            array (
                'id' => 56,
                'name' => '表单基础：全部',
                'slug' => 'hardware.all',
                'http_method' => '',
                'http_path' => 'part/tracks*,part/records*,part/categories*',
                'order' => 29,
                'parent_id' => 16,
                'created_at' => '2020-11-19 13:38:18',
                'updated_at' => '2020-12-28 16:25:16',
            ),
            52 => 
            array (
                'id' => 57,
                'name' => '表单基础：只读',
                'slug' => 'staff.read-only',
                'http_method' => 'GET',
                'http_path' => 'staff/records*,staff/departments*',
                'order' => 38,
                'parent_id' => 17,
                'created_at' => '2020-11-19 13:40:44',
                'updated_at' => '2020-12-28 16:25:16',
            ),
            53 => 
            array (
                'id' => 58,
                'name' => '表单基础：全部',
                'slug' => 'staff.all',
                'http_method' => '',
                'http_path' => 'staff/records*,staff/departments*',
                'order' => 39,
                'parent_id' => 17,
                'created_at' => '2020-11-19 13:41:10',
                'updated_at' => '2020-12-28 16:25:16',
            ),
            54 => 
            array (
                'id' => 59,
                'name' => '表单基础：只读',
                'slug' => 'service.read-only',
                'http_method' => 'GET',
                'http_path' => 'service/records*,service/tracks*,service/issues*',
                'order' => 44,
                'parent_id' => 18,
                'created_at' => '2020-11-19 13:44:25',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            55 => 
            array (
                'id' => 60,
                'name' => '表单基础：全部',
                'slug' => 'service.all',
                'http_method' => '',
                'http_path' => 'service/records*,service/tracks*,service/issues*',
                'order' => 45,
                'parent_id' => 18,
                'created_at' => '2020-11-19 13:45:00',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            56 => 
            array (
                'id' => 61,
                'name' => '表单基础：只读',
                'slug' => 'check.read-only',
                'http_method' => 'GET',
                'http_path' => 'check/records*,check/tracks*',
                'order' => 53,
                'parent_id' => 19,
                'created_at' => '2020-11-19 14:00:10',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            57 => 
            array (
                'id' => 62,
                'name' => '表单基础：全部',
                'slug' => 'check.all',
                'http_method' => '',
                'http_path' => 'check/records*,check/tracks*',
                'order' => 54,
                'parent_id' => 19,
                'created_at' => '2020-11-19 14:00:45',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            58 => 
            array (
                'id' => 63,
                'name' => '表单基础：只读',
                'slug' => 'maintenance.read-only',
                'http_method' => 'GET',
                'http_path' => 'maintenance/records*',
                'order' => 60,
                'parent_id' => 20,
                'created_at' => '2020-11-19 14:01:46',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            59 => 
            array (
                'id' => 64,
                'name' => '表单基础：全部',
                'slug' => 'maintenance.all',
                'http_method' => '',
                'http_path' => 'maintenance/records*',
                'order' => 61,
                'parent_id' => 20,
                'created_at' => '2020-11-19 14:02:10',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            60 => 
            array (
                'id' => 65,
                'name' => '表单基础：只读',
                'slug' => 'vendor.read-only',
                'http_method' => 'GET',
                'http_path' => 'vendor/records*',
                'order' => 65,
                'parent_id' => 21,
                'created_at' => '2020-11-19 14:03:07',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            61 => 
            array (
                'id' => 66,
                'name' => '表单基础：全部',
                'slug' => 'vendor.all',
                'http_method' => '',
                'http_path' => 'vendor/records*',
                'order' => 66,
                'parent_id' => 21,
                'created_at' => '2020-11-19 14:03:24',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            62 => 
            array (
                'id' => 67,
                'name' => '表单基础：只读',
                'slug' => 'puchased.read-only',
                'http_method' => 'GET',
                'http_path' => 'purchased/channels*',
                'order' => 68,
                'parent_id' => 22,
                'created_at' => '2020-11-19 14:04:08',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            63 => 
            array (
                'id' => 68,
                'name' => '表单基础：全部',
                'slug' => 'purchased.all',
                'http_method' => '',
                'http_path' => 'purchased/channels*',
                'order' => 69,
                'parent_id' => 22,
                'created_at' => '2020-11-19 14:04:39',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            64 => 
            array (
                'id' => 69,
                'name' => '表单基础：只读',
                'slug' => 'version.read-only',
                'http_method' => 'GET',
                'http_path' => 'version',
                'order' => 71,
                'parent_id' => 23,
                'created_at' => '2020-11-19 14:05:14',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            65 => 
            array (
                'id' => 70,
                'name' => '动作',
                'slug' => 'version.action',
                'http_method' => '',
                'http_path' => '',
                'order' => 72,
                'parent_id' => 23,
                'created_at' => '2020-11-19 14:05:40',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            66 => 
            array (
                'id' => 72,
                'name' => '更新数据库结构',
                'slug' => 'version.migrate',
                'http_method' => '',
                'http_path' => 'version/migrate',
                'order' => 73,
                'parent_id' => 70,
                'created_at' => '2020-11-19 14:06:39',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            67 => 
            array (
                'id' => 73,
                'name' => '折旧规则',
                'slug' => 'depreciation_rule',
                'http_method' => '',
                'http_path' => '',
                'order' => 74,
                'parent_id' => 0,
                'created_at' => '2020-12-19 01:16:23',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            68 => 
            array (
                'id' => 74,
                'name' => '表单基础：只读',
                'slug' => 'depreciation_rule.read-only',
                'http_method' => 'GET',
                'http_path' => 'depreciation/rules*',
                'order' => 75,
                'parent_id' => 73,
                'created_at' => '2020-12-19 01:17:19',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            69 => 
            array (
                'id' => 75,
                'name' => '表单基础：全部',
                'slug' => 'depreciation_rule.all',
                'http_method' => '',
                'http_path' => 'depreciation/rules*',
                'order' => 76,
                'parent_id' => 73,
                'created_at' => '2020-12-19 01:18:30',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            70 => 
            array (
                'id' => 76,
                'name' => '站点配置',
                'slug' => 'configuration',
                'http_method' => '',
                'http_path' => '',
                'order' => 77,
                'parent_id' => 0,
                'created_at' => '2020-12-19 01:18:30',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            71 => 
            array (
                'id' => 77,
                'name' => '表单基础：只读',
                'slug' => 'configuration.read-only',
                'http_method' => 'GET',
                'http_path' => 'configurations*',
                'order' => 78,
                'parent_id' => 76,
                'created_at' => '2020-12-19 01:18:30',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            72 => 
            array (
                'id' => 78,
                'name' => '表单基础：全部',
                'slug' => 'configuration.all',
                'http_method' => '',
                'http_path' => 'configurations*',
                'order' => 79,
                'parent_id' => 76,
                'created_at' => '2020-12-19 01:18:30',
                'updated_at' => '2020-12-29 23:52:05',
            ),
            73 => 
            array (
                'id' => 79,
                'name' => '设备批量删除',
                'slug' => 'device.record.batch.delete',
                'http_method' => '',
                'http_path' => '',
                'order' => 11,
                'parent_id' => 7,
                'created_at' => '2020-12-28 16:24:23',
                'updated_at' => '2020-12-28 16:24:30',
            ),
            74 => 
            array (
                'id' => 80,
                'name' => '软件批量删除',
                'slug' => 'software.record.batch.delete',
                'http_method' => '',
                'http_path' => '',
                'order' => 22,
                'parent_id' => 24,
                'created_at' => '2020-12-28 16:24:50',
                'updated_at' => '2020-12-28 16:25:16',
            ),
            75 => 
            array (
                'id' => 81,
                'name' => '配件批量删除',
                'slug' => 'part.record.batch.delete',
                'http_method' => '',
                'http_path' => '',
                'order' => 32,
                'parent_id' => 30,
                'created_at' => '2020-12-28 16:25:06',
                'updated_at' => '2020-12-28 16:25:16',
            ),
            76 => 
            array (
                'id' => 82,
                'name' => '雇员批量删除',
                'slug' => 'staff.record.batch.delete',
                'http_method' => '',
                'http_path' => '',
                'order' => 42,
                'parent_id' => 36,
                'created_at' => '2020-12-29 23:51:57',
                'updated_at' => '2020-12-29 23:52:05',
            ),
        ));
        
        
    }
}