<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DeviceRecordsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('device_records')->delete();
        
        \DB::table('device_records')->insert(array (
            0 => 
            array (
                'id' => 1,
                'description' => NULL,
                'category_id' => 13,
                'vendor_id' => 19,
                'mac' => NULL,
                'ip' => NULL,
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => 'BBBB_archive',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-18 10:56:06',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            1 => 
            array (
                'id' => 2,
                'description' => NULL,
                'category_id' => 14,
                'vendor_id' => 20,
                'mac' => NULL,
                'ip' => NULL,
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => 'AAAA_archive',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-18 10:58:40',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            2 => 
            array (
                'id' => 3,
                'description' => NULL,
                'category_id' => 15,
                'vendor_id' => 21,
                'mac' => NULL,
                'ip' => NULL,
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => NULL,
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-18 10:58:40',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            3 => 
            array (
                'id' => 4,
                'description' => NULL,
                'category_id' => 16,
                'vendor_id' => 22,
                'mac' => NULL,
                'ip' => NULL,
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => NULL,
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-18 10:59:08',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            4 => 
            array (
                'id' => 5,
                'description' => NULL,
                'category_id' => 17,
                'vendor_id' => 23,
                'mac' => NULL,
                'ip' => NULL,
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => NULL,
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-18 10:59:08',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            5 => 
            array (
                'id' => 6,
                'description' => NULL,
                'category_id' => 18,
                'vendor_id' => 24,
                'mac' => NULL,
                'ip' => NULL,
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => NULL,
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-18 13:13:22',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            6 => 
            array (
                'id' => 7,
                'description' => NULL,
                'category_id' => 19,
                'vendor_id' => 25,
                'mac' => NULL,
                'ip' => NULL,
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => NULL,
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-18 13:13:22',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            7 => 
            array (
                'id' => 8,
                'description' => NULL,
                'category_id' => 20,
                'vendor_id' => 26,
                'mac' => NULL,
                'ip' => NULL,
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => NULL,
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-18 13:17:14',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            8 => 
            array (
                'id' => 9,
                'description' => NULL,
                'category_id' => 21,
                'vendor_id' => 27,
                'mac' => NULL,
                'ip' => NULL,
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => NULL,
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-18 13:17:14',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            9 => 
            array (
                'id' => 10,
                'description' => NULL,
                'category_id' => 22,
                'vendor_id' => 28,
                'mac' => NULL,
                'ip' => NULL,
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => NULL,
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-18 13:20:03',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            10 => 
            array (
                'id' => 11,
                'description' => NULL,
                'category_id' => 23,
                'vendor_id' => 29,
                'mac' => NULL,
                'ip' => NULL,
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => NULL,
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-18 13:20:03',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            11 => 
            array (
                'id' => 12,
                'description' => NULL,
                'category_id' => 24,
                'vendor_id' => 30,
                'mac' => NULL,
                'ip' => NULL,
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => NULL,
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-18 13:20:15',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            12 => 
            array (
                'id' => 13,
                'description' => NULL,
                'category_id' => 25,
                'vendor_id' => 31,
                'mac' => NULL,
                'ip' => NULL,
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => NULL,
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-18 13:20:15',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            13 => 
            array (
                'id' => 14,
                'description' => NULL,
                'category_id' => 26,
                'vendor_id' => 32,
                'mac' => NULL,
                'ip' => NULL,
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => NULL,
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-18 21:05:58',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            14 => 
            array (
                'id' => 15,
                'description' => NULL,
                'category_id' => 1,
                'vendor_id' => 1,
                'mac' => NULL,
                'ip' => NULL,
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => 'BBBBB_archive',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-23 19:45:28',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            15 => 
            array (
                'id' => 16,
                'description' => NULL,
                'category_id' => 27,
                'vendor_id' => 33,
                'mac' => NULL,
                'ip' => NULL,
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => 'ftQhP1dPfq_archive',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 08:18:38',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            16 => 
            array (
                'id' => 17,
                'description' => NULL,
                'category_id' => 28,
                'vendor_id' => 34,
                'mac' => NULL,
                'ip' => NULL,
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => 'ywzpWqaRAf_archive',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 08:18:39',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            17 => 
            array (
                'id' => 18,
                'description' => NULL,
                'category_id' => 29,
                'vendor_id' => 35,
                'mac' => NULL,
                'ip' => NULL,
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => 'r4DC8apIaU_archive',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 08:18:39',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            18 => 
            array (
                'id' => 19,
                'description' => NULL,
                'category_id' => 30,
                'vendor_id' => 36,
                'mac' => NULL,
                'ip' => NULL,
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => 'Jk2naP4tRe_archive',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 08:18:39',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            19 => 
            array (
                'id' => 20,
                'description' => NULL,
                'category_id' => 13,
                'vendor_id' => 19,
                'mac' => '',
                'ip' => '',
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => 'BBBB_archive',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 16:47:25',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            20 => 
            array (
                'id' => 21,
                'description' => NULL,
                'category_id' => 14,
                'vendor_id' => 20,
                'mac' => '',
                'ip' => '',
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => 'AAAA_archive',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 16:47:25',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            21 => 
            array (
                'id' => 22,
                'description' => NULL,
                'category_id' => 13,
                'vendor_id' => 19,
                'mac' => '',
                'ip' => '',
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => 'BBBB_archive',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 16:47:32',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            22 => 
            array (
                'id' => 23,
                'description' => NULL,
                'category_id' => 14,
                'vendor_id' => 20,
                'mac' => '',
                'ip' => '',
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => 'AAAA_archive',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 16:47:32',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            23 => 
            array (
                'id' => 24,
                'description' => NULL,
                'category_id' => 13,
                'vendor_id' => 19,
                'mac' => '',
                'ip' => '',
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => 'BBBB_archive',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 16:48:18',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            24 => 
            array (
                'id' => 25,
                'description' => NULL,
                'category_id' => 14,
                'vendor_id' => 20,
                'mac' => '',
                'ip' => '',
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => 'AAAA_archive',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 16:48:18',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            25 => 
            array (
                'id' => 26,
                'description' => NULL,
                'category_id' => 13,
                'vendor_id' => 19,
                'mac' => '',
                'ip' => '',
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => 'BBBB',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 16:48:25',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            26 => 
            array (
                'id' => 27,
                'description' => NULL,
                'category_id' => 14,
                'vendor_id' => 20,
                'mac' => '',
                'ip' => '',
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => 'AAAA',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 16:48:25',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            27 => 
            array (
                'id' => 28,
                'description' => NULL,
                'category_id' => 15,
                'vendor_id' => 21,
                'mac' => '',
                'ip' => '',
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => '1',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 16:48:25',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            28 => 
            array (
                'id' => 29,
                'description' => NULL,
                'category_id' => 16,
                'vendor_id' => 22,
                'mac' => '',
                'ip' => '',
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => '2',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 16:48:25',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            29 => 
            array (
                'id' => 30,
                'description' => NULL,
                'category_id' => 17,
                'vendor_id' => 23,
                'mac' => '',
                'ip' => '',
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => '3',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 16:48:25',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            30 => 
            array (
                'id' => 31,
                'description' => NULL,
                'category_id' => 18,
                'vendor_id' => 24,
                'mac' => '',
                'ip' => '',
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => '4',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 16:48:25',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            31 => 
            array (
                'id' => 32,
                'description' => NULL,
                'category_id' => 19,
                'vendor_id' => 25,
                'mac' => '',
                'ip' => '',
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => '5',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 16:48:25',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            32 => 
            array (
                'id' => 33,
                'description' => NULL,
                'category_id' => 20,
                'vendor_id' => 26,
                'mac' => '',
                'ip' => '',
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => '6',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 16:48:25',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            33 => 
            array (
                'id' => 34,
                'description' => NULL,
                'category_id' => 21,
                'vendor_id' => 27,
                'mac' => '',
                'ip' => '',
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => '7',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 16:48:25',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            34 => 
            array (
                'id' => 35,
                'description' => NULL,
                'category_id' => 22,
                'vendor_id' => 28,
                'mac' => '',
                'ip' => '',
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => '8',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 16:48:25',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            35 => 
            array (
                'id' => 36,
                'description' => NULL,
                'category_id' => 23,
                'vendor_id' => 29,
                'mac' => '',
                'ip' => '',
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => '9',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 16:48:25',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            36 => 
            array (
                'id' => 37,
                'description' => NULL,
                'category_id' => 24,
                'vendor_id' => 30,
                'mac' => '',
                'ip' => '',
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => '10',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 16:48:25',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            37 => 
            array (
                'id' => 38,
                'description' => NULL,
                'category_id' => 25,
                'vendor_id' => 31,
                'mac' => '',
                'ip' => '',
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => '11',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 16:48:25',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            38 => 
            array (
                'id' => 39,
                'description' => NULL,
                'category_id' => 26,
                'vendor_id' => 32,
                'mac' => '',
                'ip' => '',
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => '12',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 16:48:25',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            39 => 
            array (
                'id' => 40,
                'description' => NULL,
                'category_id' => 1,
                'vendor_id' => 1,
                'mac' => '',
                'ip' => '',
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => 'BBBBB',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 16:48:25',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            40 => 
            array (
                'id' => 41,
                'description' => NULL,
                'category_id' => 27,
                'vendor_id' => 33,
                'mac' => '',
                'ip' => '',
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => 'ftQhP1dPfq',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 16:48:25',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            41 => 
            array (
                'id' => 42,
                'description' => NULL,
                'category_id' => 28,
                'vendor_id' => 34,
                'mac' => '',
                'ip' => '',
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => 'ywzpWqaRAf',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 16:48:25',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            42 => 
            array (
                'id' => 43,
                'description' => NULL,
                'category_id' => 29,
                'vendor_id' => 35,
                'mac' => '',
                'ip' => '',
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => 'r4DC8apIaU',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 16:48:25',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            43 => 
            array (
                'id' => 44,
                'description' => NULL,
                'category_id' => 30,
                'vendor_id' => 36,
                'mac' => '',
                'ip' => '',
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => 'Jk2naP4tRe',
                'deleted_at' => '2021-03-24 17:18:46',
                'created_at' => '2021-03-24 16:48:25',
                'updated_at' => '2021-03-24 17:18:46',
                'test3' => '',
                'test2' => '',
            ),
            44 => 
            array (
                'id' => 45,
                'description' => NULL,
                'category_id' => 1,
                'vendor_id' => 6,
                'mac' => NULL,
                'ip' => NULL,
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => 2500.0,
                'purchased' => '2021-03-24',
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => 'KD-11112',
                'deleted_at' => NULL,
                'created_at' => '2021-03-24 19:25:29',
                'updated_at' => '2021-03-24 20:13:49',
                'test3' => '',
                'test2' => '',
            ),
            45 => 
            array (
                'id' => 46,
                'description' => NULL,
                'category_id' => 1,
                'vendor_id' => 1,
                'mac' => NULL,
                'ip' => NULL,
                'photo' => NULL,
                'ssh_username' => NULL,
                'ssh_password' => NULL,
                'ssh_port' => NULL,
                'price' => NULL,
                'purchased' => NULL,
                'expired' => NULL,
                'purchased_channel_id' => NULL,
                'depreciation_rule_id' => NULL,
                'asset_number' => 'AAAAAAA',
                'deleted_at' => NULL,
                'created_at' => '2021-03-27 12:32:31',
                'updated_at' => '2021-03-27 12:32:31',
                'test3' => 'A',
                'test2' => '2222',
            ),
        ));
        
        
    }
}